### ISSUE TITLE
Error in querySelector

### ISSUE THREAD

**Issue by auveele** [matt8707/kiosk-mode#10]
I was using the "Custom-Header" component, until it has been discontinued by the developer. I have installed this addon from HACS, but I get the following error.

```
Uncaught TypeError: home_assistant_main.shadowRoot.querySelector(...).shadowRoot.querySelector(...) is null
    <anonymous> https://XX/hacsfiles/kiosk-mode/kiosk-mode.js:7
```

**Comment by matt8707** [comment]
Does it work despite the error?

**Comment by auveele** [comment]
No, it doesn't work..

**Comment by KTibow** [comment]
That's because either it deleted the header element, or you upgraded to 0.117.

**Comment by KTibow** [comment]
Just upgrade, it has a built-in compact header.

**Comment by auveele** [comment]
I just upgraded to version 117 and it didn't work. It was very strange because if I ran the JS code in the console, it would not give me the error.

I have cleared all cookies and browser cache, and it has worked.

Thank you and excuse me.
