### ISSUE TITLE
Fullscreen support &fullscreen

### ISSUE THREAD

**Issue by yevon** [matt8707/kiosk-mode#13]
This is working nicely with my tablet, but I would need a fullscreen mode option. For example adding ?kiosk&fullscreen would execute  browser in full screen mode.

var elem = document.documentElement;

/* View in fullscreen */
function openFullscreen() {
  if (elem.requestFullscreen) {
    elem.requestFullscreen();
  } else if (elem.webkitRequestFullscreen) { /* Safari */
    elem.webkitRequestFullscreen();
  } else if (elem.msRequestFullscreen) { /* IE11 */
    elem.msRequestFullscreen();
  }
}

**Comment by maykar** [comment]
For security reasons you cannot trigger full screen in any browser without some user interaction. The code that you posted there is providing the function to trigger full screen, but that would need to be tied to a button or something and would need to happen each time the app is opened. Just adding a full screen param to the URL is not enough.

**Comment by yevon** [comment]
That's true, I found an alternative, I will just use Full Kiosk Browser app in conjunction with this extension I can achiveve desired result. You can close this, thanks!
