### ISSUE TITLE
Adding path: kiosk doesnt hide it

### ISSUE THREAD

**Issue by skank01** [matt8707/kiosk-mode#21]
I tried putting the "path: kiosk" into the ui-lovelace and my other dashboards.yaml file, but it doesnt hide.
Tried putting it in the "dashboard pages" like "home" and my other pages, doesnt work either

When i put ?kiosk in the url, it does work..

Question: will path: hide_header also work?

**Comment by KTibow** [comment]
Where is this documented?

**Comment by skank01** [comment]
https://github.com/matt8707/kiosk-mode

**Comment by KTibow** [comment]
Does reloading fix it?

**Comment by maykar** [comment]
It's in the readme under usage, but currently will only work if you refresh the page while on the view with the keyword in the URL. I'll consider adding trigger for when switching between views, but I'm thinking of better ways to implement that kind of functionality.

**Comment by maykar** [comment]
I'm not sure if using paths like that should really be an option now that caching is a thing, but maybe I'm not seeing the use case here?

**Comment by skank01** [comment]
reloading doesnt work (unless i put it in the url)

I got 2 dashboards one for mobile and one for tablet, it would be cool if i can have only header  hided for tablet and everything for mobile

If i could add it in the yaml file, it would rock

**Comment by skank01** [comment]
Look here, thats my code for default dashoard
https://github.com/skank01/Home-Assistant

I have my ui-lovelace.yaml and inside the folder lovelace\views i have my home.yaml and other pages

Do i need to put it in my ui-lovelace file or inde home.yaml and all other pages?

**Comment by skank01** [comment]
i could enter it iside the url for the tabel cause its using fullykiosk browser

but for my smartphones which are using the homeassistant app, i cannot adjust its url or can i?

**Comment by maykar** [comment]
Honestly, the cache feature is best way to handle this on your tablet. On the tablet add this to your URL `?hide_header&cache` and hit enter. Then it will be saved in the devices cache and it will always hide the header, no need to do it again unless you clear the cache.

I'll think about the best way to adjust this for other scenarios, but for the home assistant app you could use the path on the first view that is visible when opening the app and add whatever option you want there, like `path: "kiosk&cache"`

**Comment by skank01** [comment]
Ok for the tablet
For the smartphone im not sure if i understand you
the first view is the "home" yaml
but setting the path in that file doesnt work

**Comment by maykar** [comment]
Yeah, setting it there is a bad idea anyhow since it would change every device. I'll try to think of the best way to make this companion app friendly, since they don't have a refresh option.

**Comment by maykar** [comment]
Going to close this issue and make a new one. The only fix I can see for companion apps is adding config of some sort, so I'll make that a feature request.

**Comment by maykar** [comment]
Added #22
