### ISSUE TITLE
Navigate to a different dashboard show the header bar

### ISSUE THREAD

**Issue by albertorivi** [matt8707/kiosk-mode#3]
Hi,
I have setup the kiosk-mode on mine dashboard. It work well when I load the dashboard as startup page of Fully Kiosk Browser.
The issue appear when from a button I manage the navigate action to a different dashboard.
In this case the header bar appear at the top.

Here an example of mine button that recall the navigate action:

          - type: icon
            icon: mdi:cog-outline
            ########################################################################
            title: Settings
            ########################################################################
            style:
              top: 75%
              left: 15%
              color: rgb(255, 255, 255)
              opacity: 0.1
              padding: 0.8vw
              --mdc-icon-size: 4vw
            tap_action:
              action: navigate
              navigation_path: /lovelace-settings?kiosk

If after loaded the dashboard I refresh the browser the header will be hidden correctly.

Many thanks for your help
Alberto

**Comment by KTibow** [comment]
That doesn't load kiosk-mode, kiosk-mode only loads on the first load. This could be fixable.

**Comment by KTibow** [comment]
See https://stackoverflow.com/a/33668370/12243248 @matt8707

**Comment by matt8707** [comment]
Right now it only works between views and not dashboards, which makes sense. But yes this should be fixed, help with this is appreciated.

**Comment by matt8707** [comment]
[Fixed in 1.2.0](https://github.com/matt8707/kiosk-mode/releases/tag/1.2.0)
