### ISSUE TITLE
Kiosk mode brings up the sidebar

### ISSUE THREAD

**Issue by Alindil** [matt8707/kiosk-mode#5]
Hi,
It all says it all in the title. I use the sidebar 
[https://github.com/DBuit/sidebar-card](url)
With Customer-header, I didn't have the problem. Now the whole page seems to go up a notch.
![Capture1](https://user-images.githubusercontent.com/30829631/96721659-beb88b00-13ac-11eb-804c-695d0fba862d.PNG)

**Comment by KTibow** [comment]
You're not supposed to have the sidebar active. Probably it's just doing that because usually the header takes up space.

**Comment by Alindil** [comment]
I don't quite understand your answer. This is not the standard sidebar but a custom one. The header bar being hidden, I don't understand why it takes up space.

**Comment by KTibow** [comment]
It probably finds out how much height it should take by calculating the size of the browser window, and then subtracting the normal size of the header. Except the header is hidden. Open an issue over at the card and close this one.
