### ISSUE TITLE
Video stream in Kiosk mode

### ISSUE THREAD

**Issue by mihing** [matt8707/kiosk-mode#6]
Hi!
I am using the Axis integration to display the video stream from my two cameras.
When "camera_view: live" is enabled, static picture is displayed in kiosk mode. In standard mode, I see a normal video stream.

    cards:
      - type: picture-entity
        entity: camera.m0
        camera_view: live
        show_state: false
        show_name: false

**Comment by KTibow** [comment]
What happens if you tap on the camera? This type of plugin shouldn't cause that.

**Comment by mihing** [comment]
When I click on the camera, I see a pop-up with a regular video stream.

**Comment by KTibow** [comment]
Is it live?

**Comment by mihing** [comment]
I apologize, the problem was hiding in the autoplay prohibition in my browser.
Its works!

**Comment by KTibow** [comment]
Close?

**Comment by mihing** [comment]
Yes.
