### ISSUE TITLE
Not hiding sidebar

### ISSUE THREAD

**Issue by asmegin** [matt8707/kiosk-mode#7]
I am having issues multiple issues with this addon. No matter what, the side bar remains. The top bar is iffy and works sometimes.
 
Supervisor Version 249
Operating System HassOS 4.15
Home Assistant 0.116.4

1. Sometimes only the top bar is hidden, but the page never loads.

![1](https://user-images.githubusercontent.com/1953729/97026227-1ed33c80-1527-11eb-9ab8-668bec7634d7.png)

2. Sometimes only the top bar is hidden, but it leaves a white bar at the top.

![2](https://user-images.githubusercontent.com/1953729/97026272-2abefe80-1527-11eb-88f8-39b1c661e7b2.png)

3. When I shrink or expand the sidebar, the white bar at the top goes away.

![3](https://user-images.githubusercontent.com/1953729/97026308-36122a00-1527-11eb-9b39-12de4586837d.png)

**Comment by KTibow** [comment]
1. Does this happen without kiosk mode?
2. **Applies to both #1 and #2** Leave devtools open, and try to recreate this. When it happens, use the button in the upper-left part of your browser's devtools and click on the empty space. Send a screenshot of devtools.
3. You can also trigger this by resizing the window.

**Comment by asmegin** [comment]
1. This does not happen without kiosk-mode.
2. Looks like the blank page is caused by:

(a) padding-top of 64, which turns to 0 when the side-bar is resized
![1](https://user-images.githubusercontent.com/1953729/97040667-441e7580-153c-11eb-86ea-58221d42e05d.jpg)

(b) the floorplan-card custom element occasionally refusing to be found:
![2](https://user-images.githubusercontent.com/1953729/97040738-62847100-153c-11eb-8f52-8333d8783418.jpg)
![3](https://user-images.githubusercontent.com/1953729/97040747-657f6180-153c-11eb-94da-872c35931e96.jpg)

I'm gonna guess it's related to the floorplan-card and look into that.

**Comment by KTibow** [comment]
Although the white bar at the top is odd, because it does continuously dispatch resizing:
https://github.com/matt8707/kiosk-mode/blob/d65488c6e9e0b0ec95e9c3203dae0ce7ba5d526f/kiosk-mode.js#L23-L28

**Comment by asmegin** [comment]
Hmm not sure what the issue is then. Here is a video of what happens:

![a](https://user-images.githubusercontent.com/1953729/97046287-2570ac80-1545-11eb-98b2-538714a7c5d0.gif)

**Comment by asmegin** [comment]
The only error I'm seeing is:

`TypeError: Cannot read property 'click' of null
    at kiosk-mode.js:22`
