### ISSUE TITLE
FR: add option for menu in footer

### ISSUE THREAD

**Issue by Mariusthvdb** [matt8707/kiosk-mode#73]
Hey Ryan!
hope you're doing well.
last time we spoke was during some big transitions.

Anyways, seems the latest Ha update to 2021.11 finally forces me to move away from Custom Header (which has worked perfectly up to now) because it suddenly doesnt show the vertical-dots anymore (Bram said they moved from `mwc-icon-button` to `ha-icon-button`)

long story short: I made a new dashboard, admin only, and added your Kiosk-mode for the kiosk-mode ;-) also, I learned we can use the hide options, which replace many of the CH options .
Main functionality lost between CH and KM is the option to show the header in the footer. It's what I did: 

Mobile: show title ( `{{viewTitle}}` )in the top, menu in the footer. 
Desktop: show menu in the header, title in the footer.

Would it be at all possible to add an option to move the header to the footer? It would almost be the perfect solution for replacing CH with Kiosk-mode and the builtin HA options.

(ofc, CH was unparalleled in assigning views to users, but thats another issue I am working on...and replacing the 3 dots with something useful, though that might be beyond the purpose of Kiosk-mode ;-) )

Hope you can have a look, and add `menu_in_footer`.

thanks!

**Comment by maykar** [comment]
Hey Marius, long time no see!

The last 2 updates added visibility options for the overflow dots and sidebar menu icon. I was pretty resistant to the additions, not wanting to turn this into something like Custom Header and even closed FRs related to the features. If it weren't for the fact that these additions were PRs from others, they probably wouldn't have been included.

Footer mode is something that I'd consider out of the scope of this one, unfortunately, but that doesn't mean I'm not willing to work on it as it's own project or for core.

Things have been pretty crazy for me recently and only now am I slowly starting to return to working on stuff. I'm currently rewriting Upcoming Media Card from scratch (desperately needed) and will be working on needed updates to other projects soon as well.

Consider this on my TODO list, just not for this project.

Thanks!
