### ISSUE TITLE
Feature Request: Hide Title

### ISSUE THREAD

**Issue by Johmpa** [matt8707/kiosk-mode#9]
I have been using the now discontinued Custom Header project and the feature I used there was to hide the Title but leave the Navigation header. I have multiple dashboards views that I switch between on my wall-mounted display and that option enabled navigation but saved one line of screen space.

Please consider replicating this mode in your project.

**Comment by matt8707** [comment]
Well, you’re in luck. You can `?hide_sidebar` and 0.117 release tomorrow introduces a compact header.

**Comment by Johmpa** [comment]
Well, I'll be damned. Great news!

**Comment by KTibow** [comment]
0.117 has a **bulky compact header**. You have to set header-height in your theme:
![image](https://user-images.githubusercontent.com/10727862/97310340-56403280-1820-11eb-8bf5-377363fe454e.png)

**Comment by Johmpa** [comment]
Thanks for the tip. Regardless it'll be a big improvement for me.
